apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-config-exporter
  namespace: monitoring
  labels:
    app: istio-config-exporter
    component: exporter
    ops: "true"
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: istio-config-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'istio_config_virtualservice_spec_uri_host_weight|istio_config_destinationrule_spec_host_trafficpolicy_loadbalancer_localitylbsetting_distribute_weight'
          action: keep
